---
version: 1.1.2
domain: wormstorysearch.com
admin_ip: 70.185.183.167
spacebattles:
  site_url: https://forums.spacebattles.com
  username: HomeTurf
  password: 22k0M8gyE6W4Yar
  max_pages: 200
sufficientvelocity:
  site_url: https://forums.sufficientvelocity.com
  username: HomeTurf
  password: 22k0M8gyE6W4Yar
  max_pages: 200
